apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cb-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/R2wenD2/cb
